# Generated by Django 4.2.2 on 2023-06-23 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 23, 21, 5, 53, 267417, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 23, 21, 5, 53, 267061, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
