# Generated by Django 4.2.2 on 2023-06-25 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0005_alter_answer_answer_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 25, 19, 50, 6, 537093, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 25, 19, 50, 6, 536711, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
