# Generated by Django 4.2.2 on 2023-06-25 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_answer_answer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 20, 6, 31, 314503, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 20, 6, 31, 312037, tzinfo=datetime.timezone.utc)),
        ),
    ]
