# Generated by Django 4.2.2 on 2023-06-26 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_answer_answer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 14, 57, 11, 712122, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 14, 57, 11, 709777, tzinfo=datetime.timezone.utc)),
        ),
    ]
