# Generated by Django 4.2.2 on 2023-06-27 18:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0013_alter_answer_answer_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 27, 18, 33, 8, 611667, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 27, 18, 33, 8, 610975, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="questions.answer",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="questions.question",
                    ),
                ),
            ],
        ),
    ]
