# Generated by Django 4.2.2 on 2023-06-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0014_alter_answer_answer_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
